# Generated by Django 4.1.2 on 2022-10-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
                ('codigo_de_barras', models.CharField(max_length=13)),
                ('codigo_interno', models.CharField(max_length=10)),
                ('grupo', models.CharField(choices=[('0', 'Geral'), ('1', 'Mercearia'), ('2', 'Frios/Congelados'), ('3', 'Padaria'), ('4', 'Hortifrute')], default='0', max_length=1)),
                ('data_de_criacao', models.DateField()),
            ],
        ),
    ]
